CREATE TABLE IF NOT EXISTS `success_stories` (
    `id`                    BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `title`                 VARCHAR(255) NOT NULL,
    `slug`                  VARCHAR(255) NOT NULL UNIQUE,
    `excerpt`               TEXT NOT NULL,
    `story`                 LONGTEXT NOT NULL,
    `person_name`           VARCHAR(100) NOT NULL,
    `person_age`            TINYINT UNSIGNED NULL,
    `person_gender`         ENUM('male','female','other') NOT NULL DEFAULT 'male',
    `division`              VARCHAR(60) NOT NULL,
    `district`              VARCHAR(60) NULL,
    `missing_date`          DATE NULL,
    `found_date`            DATE NULL,
    `cover_image_url`       VARCHAR(500) NULL,
    `cover_image_public_id` VARCHAR(255) NULL,
    `missing_report_id`     BIGINT UNSIGNED NULL,
    `found_report_id`       BIGINT UNSIGNED NULL,
    `published_by`          BIGINT UNSIGNED NOT NULL,
    `is_published`          TINYINT(1) NOT NULL DEFAULT 0,
    `published_at`          TIMESTAMP NULL,
    `featured`              TINYINT(1) NOT NULL DEFAULT 0,
    `views`                 INT UNSIGNED NOT NULL DEFAULT 0,
    `tag`                   VARCHAR(60) NOT NULL DEFAULT 'পুনর্মিলিত',
    `created_at`            TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at`            TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT `fk_ss_published_by` FOREIGN KEY (`published_by`) REFERENCES `users` (`id`) ON DELETE RESTRICT,
    INDEX `idx_ss_is_published` (`is_published`),
    INDEX `idx_ss_featured` (`featured`),
    INDEX `idx_ss_published_at` (`published_at`),
    INDEX `idx_ss_division` (`division`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;